name: build
on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: "20 16 * * 0"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
      - name: Check formatting
        run: crystal tool format --check
      - name: Install shard dependencies
        run: shards install
      - name: Run tests
        run: crystal spec
