# This CI job installs Crystal and shard dependencies, then executes `crystal spec` to run the test suite
# More configuration options are available at https://crystal-lang.github.io/install-crystal/configurator.html
name: build
on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: "20 16 * * 0"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download source
        uses: actions/checkout@v3
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install shards
        run: shards update
      - name: Run tests
        run: crystal spec --order=random
      - name: Check formatting
        run: crystal tool format --check
        if: matrix.os == 'ubuntu-latest'
